export const LANDING = "/";
export const LISTING = "/listing/:id";
export const LISTINGS = "/listings"; // temp
export const ENTRY = "/entry";
export const USER_PROFILE = "users/:id";
export const HOST_PROFILE = "hosts/:id";
export const LISTINGS_BY_SEARCH = "/listings/:city";
export const LISTINGS_BY_REGION = "/listings/:region";
export const LISTINGS_BY_TYPE = "/listings/:type";
